# Generated by Django 4.0.1 on 2022-01-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='The name of the project', max_length=200)),
                ('cracker', models.CharField(help_text='The name of the developer who cracked the interview', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peck.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caffer.project')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='RoleInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('projectdeveloper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='caffer.projectdeveloper')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='peck.role')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='projectdeveloper',
            name='role_in_project',
            field=models.ManyToManyField(through='caffer.RoleInProject', to='peck.Role'),
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ManyToManyField(help_text='The name of the developers contributed to the project on the project', through='caffer.ProjectDeveloper', to='peck.Developer', verbose_name='developers'),
        ),
    ]
