# Generated by Django 3.2.12 on 2022-02-21 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caffer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleinproject",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2022, 2, 21, 16, 17, 16, 914769)
            ),
        ),
    ]
