# Generated by Django 3.2.12 on 2022-03-04 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caffer", "0002_alter_roleinproject_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleinproject",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2022, 3, 4, 17, 5, 58, 259648)
            ),
        ),
    ]
