# Generated by Django 3.2.12 on 2022-02-22 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caffer", "0005_alter_roleinproject_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleinproject",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2022, 2, 22, 13, 20, 1, 171076)
            ),
        ),
    ]
