# Generated by Django 4.0.3 on 2022-07-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_delete_interviewer_alter_interviewupdate_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewupdate',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview.interviewupdate'),
        ),
    ]
