# Generated by Django 4.0.3 on 2022-07-27 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_interviewupdate_follow_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript')], max_length=20)),
                ('level', models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], max_length=20)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_domain',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_openings',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_requride',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=105, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_openings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='perks_and_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=models.CharField(choices=[('python', 'Python Developer'), ('react', 'React Developer')], default='python', max_length=12),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.interviewupdate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.question')),
            ],
        ),
    ]
