# Generated by Django 4.0.1 on 2022-01-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whale', '0002_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='pricey',
            new_name='pricex',
        ),
    ]
