# Generated by Django 3.2.12 on 2022-02-15 07:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("git_url", models.URLField()),
                ("git_username", models.CharField(max_length=50)),
                ("user_adress", models.TextField()),
                ("phone_number", models.CharField(max_length=12)),
                ("qualification", models.CharField(max_length=20)),
                ("technology", models.CharField(max_length=50)),
                ("project_description", models.TextField()),
                ("team_leader", models.IntegerField()),
                ("team_memeber_names", models.TextField()),
                (
                    "joining_date",
                    models.DateField(
                        default=datetime.datetime(2022, 2, 15, 13, 22, 14, 932778)
                    ),
                ),
                ("separation_date", models.DateField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=100)),
                ("experiance", models.IntegerField()),
                (
                    "user_type",
                    models.CharField(
                        choices=[("student", "STUDENT"), ("employe", "EMPLOYE")],
                        max_length=20,
                    ),
                ),
                ("user_role", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
