# Generated by Django 4.0.3 on 2022-04-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdate',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
