# Generated by Django 3.2.12 on 2022-02-15 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="joining_date",
            field=models.DateField(
                default=datetime.datetime(2022, 2, 15, 13, 27, 42, 262170)
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="team_leader",
            field=models.CharField(max_length=50),
        ),
    ]
