# Generated by Django 3.2.12 on 2022-02-22 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0006_auto_20220222_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="profile",
            field=models.FileField(blank=True, null=True, upload_to="profile"),
        ),
        migrations.AlterField(
            model_name="information",
            name="joining_date",
            field=models.DateField(
                default=datetime.datetime(2022, 2, 22, 14, 50, 48, 728039)
            ),
        ),
    ]
