# Generated by Django 3.2.12 on 2022-02-19 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sde1', 'Software Developer I'), ('sde2', 'Software Developer II'), ('sde3', 'Software Developer III'), ('sde4', 'Software Developer IV'), ('graphic_designer', 'Graphic Designer'), ('qa', 'Quality Analyst'), ('python_developer', 'Python Developer'), ('django_developer', 'Django Developer'), ('tl', 'Team_leader'), ('project_manager', 'Project Manager')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ManyToManyField(to='peck.Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
