# Generated by Django 4.0.1 on 2022-01-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peck", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role",
            field=models.CharField(
                choices=[("developer", "developer"), ("designer", "designer")],
                max_length=30,
                unique=True,
            ),
        ),
    ]
