# Generated by Django 4.0.1 on 2022-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peck', '0002_alter_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
